server:
  port: 8080
#feign:
#  hystrix:
#    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oasys?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  application:
    name: oasys-web
  thymeleaf:
    prefix: classpath:/WEB-INF/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
logging:
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations:
    - classpath:/mapping/*.xml
  type-aliases-package: cn.oasys.web.model.pojo
  configuration:
    map-underscore-to-camel-case: true
#eureka:
#  #  instance:
#  #    prefer-ip-address: true
#  #    ip-address: 127.0.0.1
#  #    instance-id: ${spring.application.name}###${server.port}
#  client:
#    service-url:
#      defaultZone: http://admin:admin@127.0.0.1:8100/eureka/, http://admin:admin@127.0.0.1:9100/eureka/
#    register-with-eureka: true
#    fetch-registry: true
