server:
  port: 8100
#  port: 9100
spring:
  security:
    basic:
      enable: true
    user:
      name: admin
      password: admin
  application:
    name: oasys-eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    register-with-eureka: false
    fetch-registry: false